import { FormEvent, useEffect, useState } from "react";
import { ArrowLeft, Loader2, Save, Store } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { useAuth } from "../../contexts/AuthContext";
import { supabase } from "../../lib/supabase";

type StoreRow = { id: string; name: string; name_en: string; city: string; district: string; address: string; phone: string; hours: { primary?: string; secondary?: string }; image_url: string; map_url: string; is_active: boolean; manager_notes: string };

export default function StoreInfo() {
  const { role, storeAssignments, hasStorePermission } = useAuth();
  const navigate = useNavigate();
  const [stores, setStores] = useState<StoreRow[]>([]); const [storeId, setStoreId] = useState(""); const [form, setForm] = useState<StoreRow | null>(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  useEffect(() => { const ids = storeAssignments.map((item) => item.store_location_id); let query = supabase.from("store_locations").select("id,name,name_en,city,district,address,phone,hours,image_url,map_url,is_active,manager_notes").order("name"); if (role !== "admin" && role !== "superadmin" && ids.length) query = query.in("id", ids); query.then(({ data, error }) => { if (error) setMessage(error.message); const rows = (data || []) as StoreRow[]; setStores(rows); setStoreId(rows[0]?.id || ""); setForm(rows[0] || null); setLoading(false); }); }, [role, storeAssignments]);
  useEffect(() => { const next = stores.find((store) => store.id === storeId); if (next) setForm(next); }, [storeId, stores]);
  const update = (key: keyof StoreRow, value: string | boolean) => setForm((current) => current ? { ...current, [key]: value } : current);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!form || !hasStorePermission(form.id, "info") && role !== "admin" && role !== "superadmin") { setMessage("你沒有這間門市的管理權限。"); return; } setBusy(true); const { error } = await supabase.from("store_locations").update({ name: form.name.trim(), name_en: form.name_en.trim(), city: form.city.trim(), district: form.district.trim(), address: form.address.trim(), phone: form.phone.trim(), hours: form.hours, image_url: form.image_url.trim(), map_url: form.map_url.trim(), is_active: form.is_active, manager_notes: form.manager_notes.trim(), updated_at: new Date().toISOString() }).eq("id", form.id); setMessage(error?.message || "門市資訊已儲存"); setBusy(false); };
  if (loading) return <div className="flex min-h-screen items-center justify-center"><Loader2 className="h-8 w-8 animate-spin text-amber-600" /></div>;
  return <main className="min-h-screen bg-stone-50 px-4 py-6 md:px-8"><div className="mx-auto max-w-4xl"><div className="mb-6 flex items-center justify-between gap-3"><div><p className="text-sm font-semibold tracking-[0.25em] text-amber-700">STORE PROFILE</p><h1 className="mt-1 flex items-center gap-2 text-3xl font-bold"><Store className="h-7 w-7 text-amber-600" />門市資訊</h1></div><button type="button" onClick={() => navigate("/member/store-admin")} className="rounded-xl border bg-white px-4 py-2.5 text-sm font-semibold"><ArrowLeft className="mr-1 inline h-4 w-4" />返回門市管理</button></div><div className="mb-5 rounded-2xl bg-white p-5 shadow-sm"><label className="mb-2 block text-sm font-semibold">管理門市</label><select value={storeId} onChange={(event) => setStoreId(event.target.value)} className="w-full rounded-xl border px-4 py-3">{stores.map((store) => <option key={store.id} value={store.id}>{store.name}</option>)}</select></div>{message && <p className="mb-4 rounded-xl bg-amber-50 p-3 text-sm text-amber-800">{message}</p>}{form && <form onSubmit={submit} className="rounded-2xl bg-white p-6 shadow-sm"><div className="grid gap-4 md:grid-cols-2">{([["name", "門市名稱"], ["name_en", "英文名稱"], ["city", "城市"], ["district", "區域"], ["address", "地址"], ["phone", "電話"], ["image_url", "圖片網址"], ["map_url", "地圖網址"]] as const).map(([key, label]) => <label key={key} className="text-sm font-semibold">{label}<input value={form[key] as string} onChange={(event) => update(key, event.target.value)} className="mt-2 w-full rounded-xl border px-4 py-3 font-normal" /></label>)}<label className="text-sm font-semibold">營業時間<input value={form.hours?.primary || ""} onChange={(event) => setForm({ ...form, hours: { ...form.hours, primary: event.target.value } })} className="mt-2 w-full rounded-xl border px-4 py-3 font-normal" /></label><label className="text-sm font-semibold">備註<textarea value={form.manager_notes} onChange={(event) => update("manager_notes", event.target.value)} rows={3} className="mt-2 w-full rounded-xl border px-4 py-3 font-normal" /></label></div><label className="mt-4 flex items-center gap-2 text-sm"><input type="checkbox" checked={form.is_active} onChange={(event) => update("is_active", event.target.checked)} />啟用門市</label><button disabled={busy} className="mt-5 rounded-xl bg-slate-900 px-5 py-3 font-semibold text-white disabled:opacity-40">{busy ? <Loader2 className="inline h-5 w-5 animate-spin" /> : <><Save className="mr-1 inline h-4 w-4" />儲存門市資訊</>}</button></form>}</div></main>;
}
