import { useEffect, useState } from "react";
import { ArrowLeft, Copy, Download, Loader2, Printer, QrCode } from "lucide-react";
import QRCode from "qrcode";
import { useNavigate } from "react-router-dom";
import { useAuth } from "../../contexts/AuthContext";
import { supabase } from "../../lib/supabase";

type Store = { id: string; name: string };
export default function StoreFixedQr() {
  const { role, storeAssignments } = useAuth(); const navigate = useNavigate(); const [stores, setStores] = useState<Store[]>([]); const [storeId, setStoreId] = useState(""); const [url, setUrl] = useState(""); const [qr, setQr] = useState(""); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  useEffect(() => { const ids = storeAssignments.map((item) => item.store_location_id); let query = supabase.from("store_locations").select("id,name").eq("is_active", true).order("name"); if (role !== "admin" && role !== "superadmin" && ids.length) query = query.in("id", ids); query.then(({ data, error }) => { if (error) setMessage(error.message); const rows = (data || []) as Store[]; setStores(rows); setStoreId(rows[0]?.id || ""); setLoading(false); }); }, [role, storeAssignments]);
  const loadQr = async (id: string, regenerate = false) => { if (!id) return; setBusy(true); const { data, error } = await supabase.rpc(regenerate ? "regenerate_store_qr_code" : "ensure_store_qr_code", { p_store_location_id: id }); if (error || !data?.success) setMessage(error?.message || "無法建立門市 QR Code"); else { const next = `${window.location.origin}/store/redeem/store/${data.publicToken}`; setUrl(next); setQr(await QRCode.toDataURL(next, { width: 420, margin: 2 })); setMessage(regenerate ? "門市固定 QR Code 已重設，舊 QR Code 已失效。" : "門市固定 QR Code 已準備完成。"); } setBusy(false); };
  useEffect(() => { if (storeId) void loadQr(storeId); }, [storeId]);
  if (loading) return <div className="flex min-h-screen items-center justify-center"><Loader2 className="h-8 w-8 animate-spin text-amber-600" /></div>;
  return <main className="min-h-screen bg-stone-50 px-4 py-6 md:px-8"><div className="mx-auto max-w-4xl"><div className="mb-6 flex items-center justify-between gap-3"><div><p className="text-sm font-semibold tracking-[0.25em] text-amber-700">STORE QR CODE</p><h1 className="mt-1 flex items-center gap-2 text-3xl font-bold"><QrCode className="h-7 w-7 text-amber-600" />門市固定收款 QR Code</h1><p className="mt-1 text-sm text-slate-500">張貼在櫃檯，顧客掃描後進入該門市的收款入口。</p></div><button type="button" onClick={() => navigate("/member/store-admin")} className="rounded-xl border bg-white px-4 py-2.5 text-sm font-semibold"><ArrowLeft className="mr-1 inline h-4 w-4" />返回門市管理</button></div><div className="mb-5 rounded-2xl bg-white p-5 shadow-sm"><label className="mb-2 block text-sm font-semibold">門市</label><select value={storeId} onChange={(event) => setStoreId(event.target.value)} className="w-full max-w-md rounded-xl border px-4 py-3">{stores.map((store) => <option key={store.id} value={store.id}>{store.name}</option>)}</select></div>{message && <p className="mb-4 rounded-xl bg-amber-50 p-3 text-sm text-amber-800">{message}</p>}<section className="rounded-2xl bg-white p-6 text-center shadow-sm">{qr ? <><img src={qr} alt="門市固定收款 QR Code" className="mx-auto rounded-2xl border p-3" /><p className="mx-auto mt-4 max-w-xl break-all rounded-xl bg-stone-50 p-3 text-xs text-slate-500">{url}</p><div className="mt-4 flex flex-wrap justify-center gap-2"><a href={qr} download="nestobi-store-fixed-qr.png" className="rounded-xl border px-4 py-2 text-sm"><Download className="mr-1 inline h-4 w-4" />下載 PNG</a><button type="button" onClick={() => void navigator.clipboard.writeText(url)} className="rounded-xl border px-4 py-2 text-sm"><Copy className="mr-1 inline h-4 w-4" />複製連結</button><button type="button" onClick={() => window.print()} className="rounded-xl border px-4 py-2 text-sm"><Printer className="mr-1 inline h-4 w-4" />列印</button><button type="button" disabled={busy} onClick={() => void loadQr(storeId, true)} className="rounded-xl border border-red-200 px-4 py-2 text-sm text-red-700">重設 Token</button></div></> : <p className="py-20 text-sm text-slate-400">尚未建立 QR Code</p>}</section></div></main>;
}
