import { useEffect, useState } from "react";
import { ArrowLeft, Loader2, Shield, UserRound } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { useAuth } from "../../contexts/AuthContext";
import { supabase } from "../../lib/supabase";

type Store = { id: string; name: string };
type Manager = { id: string; user_id: string; role: string; is_active: boolean; can_manage_store_info: boolean; can_manage_products: boolean; can_manage_inventory: boolean; can_manage_points: boolean; can_manage_sales: boolean };

export default function StoreManagers() {
  const { role, storeAssignments } = useAuth(); const navigate = useNavigate(); const [stores, setStores] = useState<Store[]>([]); const [storeId, setStoreId] = useState(""); const [managers, setManagers] = useState<Manager[]>([]); const [loading, setLoading] = useState(true); const [message, setMessage] = useState("");
  useEffect(() => { const ids = storeAssignments.map((item) => item.store_location_id); let query = supabase.from("store_locations").select("id,name").eq("is_active", true).order("name"); if (role !== "admin" && role !== "superadmin" && ids.length) query = query.in("id", ids); query.then(({ data, error }) => { if (error) setMessage(error.message); const rows = (data || []) as Store[]; setStores(rows); setStoreId(rows[0]?.id || ""); setLoading(false); }); }, [role, storeAssignments]);
  useEffect(() => { if (!storeId) return; supabase.from("store_location_managers").select("id,user_id,role,is_active,can_manage_store_info,can_manage_products,can_manage_inventory,can_manage_points,can_manage_sales").eq("store_location_id", storeId).order("created_at").then(({ data, error }) => { if (error) setMessage(error.message); setManagers((data || []) as Manager[]); }); }, [storeId]);
  if (loading) return <div className="flex min-h-screen items-center justify-center"><Loader2 className="h-8 w-8 animate-spin text-amber-600" /></div>;
  return <main className="min-h-screen bg-stone-50 px-4 py-6 md:px-8"><div className="mx-auto max-w-4xl"><div className="mb-6 flex items-center justify-between gap-3"><div><p className="text-sm font-semibold tracking-[0.25em] text-amber-700">STORE TEAM</p><h1 className="mt-1 flex items-center gap-2 text-3xl font-bold"><Shield className="h-7 w-7 text-amber-600" />門市管理員</h1><p className="mt-1 text-sm text-slate-500">查看指定門市的管理員與功能權限。</p></div><button type="button" onClick={() => navigate("/member/store-admin")} className="rounded-xl border bg-white px-4 py-2.5 text-sm font-semibold"><ArrowLeft className="mr-1 inline h-4 w-4" />返回門市管理</button></div><div className="mb-5 rounded-2xl bg-white p-5 shadow-sm"><label className="mb-2 block text-sm font-semibold">管理門市</label><select value={storeId} onChange={(event) => setStoreId(event.target.value)} className="w-full max-w-md rounded-xl border px-4 py-3">{stores.map((store) => <option key={store.id} value={store.id}>{store.name}</option>)}</select></div>{message && <p className="mb-4 rounded-xl bg-amber-50 p-3 text-sm text-amber-800">{message}</p>}<section className="rounded-2xl bg-white p-5 shadow-sm"><div className="space-y-3">{managers.map((manager) => <article key={manager.id} className="rounded-xl border border-slate-200 p-4"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-3"><span className="rounded-full bg-amber-50 p-3 text-amber-700"><UserRound className="h-5 w-5" /></span><div><p className="font-semibold">{manager.user_id}</p><p className="text-sm text-slate-500">{manager.role}</p></div></div><span className={`rounded-full px-3 py-1 text-xs font-semibold ${manager.is_active ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-500"}`}>{manager.is_active ? "啟用" : "停用"}</span></div><div className="mt-3 flex flex-wrap gap-2 text-xs text-slate-600">{manager.can_manage_store_info && <span className="rounded-full bg-slate-100 px-2 py-1">門市資訊</span>}{manager.can_manage_products && <span className="rounded-full bg-slate-100 px-2 py-1">商品</span>}{manager.can_manage_inventory && <span className="rounded-full bg-slate-100 px-2 py-1">庫存</span>}{manager.can_manage_points && <span className="rounded-full bg-slate-100 px-2 py-1">點數</span>}{manager.can_manage_sales && <span className="rounded-full bg-slate-100 px-2 py-1">銷售</span>}</div></article>)}{!managers.length && <p className="py-12 text-center text-sm text-slate-400">目前沒有門市管理員</p>}</div></section></div></main>;
}
