import { useEffect, useState } from 'react';
import { Link2, MessageCircle, Unlink } from 'lucide-react';
import { supabase } from '../../lib/supabase';
import { useAuth } from '../../contexts/AuthContext';

type LineAccount = { id: string; line_user_id: string; line_display_name: string; line_picture_url: string | null; is_active: boolean; bound_at: string };
type LiffApi = { init: (options: { liffId: string }) => Promise<void>; isLoggedIn: () => boolean; login: (options?: { redirectUri?: string }) => void; getIDToken: () => string | null; getProfile: () => Promise<{ displayName?: string; pictureUrl?: string }> };
declare global { interface Window { liff?: LiffApi } }

const loadLiff = async (): Promise<LiffApi> => { if (window.liff) return window.liff; await new Promise<void>((resolve, reject) => { const script = document.createElement('script'); script.src = 'https://static.line-scdn.net/liff/edge/2/sdk.js'; script.onload = () => resolve(); script.onerror = () => reject(new Error('LINE SDK 載入失敗')); document.head.appendChild(script); }); if (!window.liff) throw new Error('LINE SDK unavailable'); return window.liff; };

export default function MemberLineBinding() {
  const { user } = useAuth(); const [account, setAccount] = useState<LineAccount | null>(null); const [loading, setLoading] = useState(true); const [working, setWorking] = useState(false); const [message, setMessage] = useState(''); const liffId = (import.meta.env.VITE_LINE_LIFF_ID || '').trim();
  useEffect(() => { const load = async () => { if (!user) return; const { data } = await supabase.from('user_line_accounts').select('id,line_user_id,line_display_name,line_picture_url,is_active,bound_at').eq('user_id', user.id).eq('is_active', true).maybeSingle(); setAccount(data as LineAccount | null); setLoading(false); }; void load(); }, [user]);
  const bind = async () => { setWorking(true); setMessage(''); try { if (!liffId) throw new Error('尚未設定 LINE LIFF ID'); const liff = await loadLiff(); await liff.init({ liffId }); if (!liff.isLoggedIn()) { liff.login({ redirectUri: window.location.href }); return; } const idToken = liff.getIDToken(); if (!idToken) throw new Error('無法取得 LINE 身分驗證'); const { data, error } = await supabase.functions.invoke('bind-line-profile', { body: { idToken } }); if (error || !data?.ok) throw new Error(data?.error || error?.message || 'LINE 綁定失敗'); setAccount(data.account as LineAccount); setMessage('LINE 綁定成功'); } catch (e) { setMessage(e instanceof Error ? e.message : 'LINE 綁定失敗'); } finally { setWorking(false); } };
  const unbind = async () => { if (!account || !window.confirm('確定解除 LINE 綁定？')) return; setWorking(true); const { error } = await supabase.from('user_line_accounts').update({ is_active: false, unbound_at: new Date().toISOString(), updated_at: new Date().toISOString() }).eq('id', account.id); setWorking(false); if (error) setMessage(error.message); else { setAccount(null); setMessage('已解除 LINE 綁定'); } };
  if (loading) return <div className="py-16 text-center text-gray-500">載入中...</div>;
  return <div className="space-y-5"><h2 className="text-xl font-bold flex items-center gap-2"><MessageCircle className="text-green-600" />LINE 綁定</h2><div className="rounded-2xl bg-white p-6 shadow-sm border border-gray-100"><p className="text-sm text-gray-600">綁定 LINE 後，可接收訂單、付款與會員服務通知。</p>{account ? <div className="mt-5 flex flex-wrap items-center justify-between gap-4 rounded-xl border border-green-100 bg-green-50 p-4"><div className="flex items-center gap-3">{account.line_picture_url ? <img src={account.line_picture_url} alt="LINE" className="h-12 w-12 rounded-full" /> : <MessageCircle className="h-10 w-10 text-green-600" />}<div><p className="font-semibold text-gray-900">{account.line_display_name}</p><p className="text-xs text-green-700">已綁定</p></div></div><button onClick={() => void unbind()} disabled={working} className="inline-flex items-center gap-2 rounded-lg border border-red-200 px-3 py-2 text-sm text-red-600"><Unlink size={16} />解除綁定</button></div> : <button onClick={() => void bind()} disabled={working} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-[#06C755] px-5 py-3 font-semibold text-white disabled:opacity-50"><Link2 size={18} />{working ? '處理中...' : '綁定 LINE 帳號'}</button>}{message && <p className="mt-4 text-sm text-gray-600">{message}</p>}</div></div>;
}
