import { useEffect, useMemo, useState } from 'react';
import { supabase } from '../../lib/supabase';
import { formatCurrency, formatDateTime } from '../../lib/utils';

type Refund = { id: string; order_id: string; merchant_order_no: string | null; newebpay_trade_no: string | null; refund_amount: number; refund_reason: string | null; refund_method: string; status: string; requested_at: string; completed_at: string | null; processed_by: string | null; admin_note: string | null };

export default function SuperAdminRefunds() {
  const [rows, setRows] = useState<Refund[]>([]); const [orders, setOrders] = useState<Record<string, any>>({}); const [filter, setFilter] = useState('all'); const [query, setQuery] = useState(''); const [loading, setLoading] = useState(true); const [message, setMessage] = useState(''); const [orderId, setOrderId] = useState(''); const [amount, setAmount] = useState(''); const [reason, setReason] = useState('');
  const load = async () => { setLoading(true); const { data, error } = await supabase.from('refunds').select('*').order('status', { ascending: true }).order('requested_at', { ascending: false }); if (error) { setMessage(error.message); setLoading(false); return; } const list = (data || []) as Refund[]; setRows(list); const ids = [...new Set(list.map(r => r.order_id))]; if (ids.length) { const { data: orderRows } = await supabase.from('orders').select('id,user_id,total_amount').in('id', ids); setOrders(Object.fromEntries((orderRows || []).map(o => [o.id, o]))); } setLoading(false); };
  useEffect(() => { void load(); }, []);
  const visible = useMemo(() => rows.filter(r => (filter === 'all' || r.status === filter) && (!query.trim() || `${r.order_id} ${r.merchant_order_no || ''} ${r.newebpay_trade_no || ''} ${orders[r.order_id]?.user_id || ''}`.toLowerCase().includes(query.toLowerCase()))), [rows, filter, query, orders]);
  const complete = async (id: string) => { if (!window.confirm('請確認已在藍新後台完成退款。')) return; const { error } = await supabase.rpc('complete_manual_refund', { p_refund_id: id }); if (error) setMessage(error.message); else { setMessage('退款已標記完成。'); await load(); } };
  const cancel = async (id: string) => { if (!window.confirm('確定取消此退款申請？')) return; const { error } = await supabase.rpc('cancel_manual_refund', { p_refund_id: id }); if (error) setMessage(error.message); else { setMessage('退款申請已取消。'); await load(); } };
  const create = async () => { const value = Number(amount); if (!orderId.trim() || !Number.isFinite(value) || value <= 0) { setMessage('請輸入有效的訂單 ID 與退款金額。'); return; } if (!window.confirm(`即將建立 NT$${value} 的退款申請，建立後仍需至藍新後台實際退款。`)) return; const { error } = await supabase.rpc('create_manual_refund', { p_order_id: orderId.trim(), p_amount: value, p_reason: reason, p_note: '' }); if (error) setMessage(error.message); else { setMessage('退款申請已建立。'); setOrderId(''); setAmount(''); setReason(''); await load(); } };
  return <div className="space-y-6"><div><h1 className="text-2xl font-bold text-gray-900">退款管理</h1><p className="mt-1 text-sm text-gray-500">藍新人工退款紀錄；請先在藍新後台完成退款，再確認完成。</p></div>{message && <div className="rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800">{message}</div>}<div className="rounded-2xl bg-white p-4 shadow-sm"><h2 className="font-semibold">建立人工退款申請</h2><div className="mt-3 flex flex-wrap gap-2"><input value={orderId} onChange={e => setOrderId(e.target.value)} placeholder="訂單 UUID" className="rounded-xl border px-3 py-2 text-sm" /><input type="number" min="1" value={amount} onChange={e => setAmount(e.target.value)} placeholder="退款金額" className="w-32 rounded-xl border px-3 py-2 text-sm" /><input value={reason} onChange={e => setReason(e.target.value)} placeholder="退款原因" className="rounded-xl border px-3 py-2 text-sm" /><button onClick={() => void create()} className="rounded-xl bg-amber-600 px-4 py-2 text-sm font-semibold text-white">申請退款</button></div></div><div className="flex flex-wrap gap-2">{['all','pending','processing','completed','cancelled','failed'].map(s => <button key={s} onClick={() => setFilter(s)} className={`rounded-xl px-3 py-2 text-sm ${filter === s ? 'bg-emerald-600 text-white' : 'bg-white text-gray-600'}`}>{s === 'all' ? '全部' : s}</button>)}<input value={query} onChange={e => setQuery(e.target.value)} placeholder="訂單／MerchantOrderNo／TradeNo／會員" className="ml-auto rounded-xl border border-gray-200 px-3 py-2 text-sm" /></div>{loading ? <p>載入中…</p> : <div className="overflow-x-auto rounded-2xl bg-white shadow-sm"><table className="min-w-full text-left text-sm"><thead className="bg-gray-50 text-gray-500"><tr>{['退款編號','訂單編號','付款金額','退款金額','退款原因','方式','狀態','建立時間','操作'].map(h => <th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody>{visible.map(r => <tr key={r.id} className="border-t border-gray-100"><td className="px-4 py-3 font-mono text-xs">{r.id.slice(0,8)}</td><td className="px-4 py-3"><div>{r.order_id.slice(0,8)}</div><div className="text-xs text-gray-400">{r.merchant_order_no || '-'}</div></td><td className="px-4 py-3">{formatCurrency(orders[r.order_id]?.total_amount || 0)}</td><td className="px-4 py-3 font-semibold">{formatCurrency(r.refund_amount)}</td><td className="px-4 py-3">{r.refund_reason || '-'}</td><td className="px-4 py-3">藍新人工</td><td className="px-4 py-3">{r.status}</td><td className="px-4 py-3 whitespace-nowrap">{formatDateTime(r.requested_at)}</td><td className="px-4 py-3 whitespace-nowrap">{r.status === 'pending' || r.status === 'processing' ? <><button onClick={() => void complete(r.id)} className="mr-2 rounded-lg bg-emerald-600 px-2 py-1 text-xs text-white">已完成退款</button>{r.status === 'pending' && <button onClick={() => void cancel(r.id)} className="rounded-lg bg-gray-100 px-2 py-1 text-xs text-gray-700">取消</button>}</> : '-'}</td></tr>)}</tbody></table>{visible.length === 0 && <p className="p-8 text-center text-gray-400">目前沒有退款紀錄</p>}</div>}</div>;
}
