/* Phase 3: smart reorder purchase order drafts */
CREATE TABLE IF NOT EXISTS public.purchase_orders (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), order_no text NOT NULL UNIQUE DEFAULT ('PO-' || to_char(now(),'YYYYMMDD') || '-' || upper(substr(replace(gen_random_uuid()::text,'-',''),1,8))), supplier_id uuid REFERENCES public.suppliers(id) ON DELETE SET NULL, status text NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','submitted','partially_received','received','cancelled')), requested_by uuid REFERENCES auth.users(id) ON DELETE SET NULL, expected_at date, notes text NOT NULL DEFAULT '', total_estimated_cost numeric NOT NULL DEFAULT 0 CHECK(total_estimated_cost >= 0), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.purchase_order_items (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), purchase_order_id uuid NOT NULL REFERENCES public.purchase_orders(id) ON DELETE CASCADE, bean_id uuid NOT NULL REFERENCES public.coffee_beans(id) ON DELETE RESTRICT, quantity numeric NOT NULL CHECK(quantity > 0), unit_cost numeric NOT NULL DEFAULT 0 CHECK(unit_cost >= 0), source text NOT NULL DEFAULT 'smart_reorder' CHECK(source IN ('smart_reorder','manual')), created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(purchase_order_id,bean_id));
CREATE INDEX IF NOT EXISTS idx_purchase_orders_status ON public.purchase_orders(status,created_at DESC);
ALTER TABLE public.purchase_orders ENABLE ROW LEVEL SECURITY; ALTER TABLE public.purchase_order_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY purchase_orders_admin_all ON public.purchase_orders FOR ALL TO authenticated USING(public.can_manage_inventory()) WITH CHECK(public.can_manage_inventory());
CREATE POLICY purchase_order_items_admin_all ON public.purchase_order_items FOR ALL TO authenticated USING(public.can_manage_inventory()) WITH CHECK(public.can_manage_inventory());
GRANT SELECT,INSERT,UPDATE ON public.purchase_orders,public.purchase_order_items TO authenticated;
CREATE OR REPLACE FUNCTION public.create_inventory_purchase_order(p_items jsonb,p_notes text DEFAULT '') RETURNS uuid LANGUAGE plpgsql SECURITY INVOKER SET search_path=public AS $$ DECLARE v_id uuid; v_item jsonb; v_total numeric:=0; BEGIN IF NOT public.can_manage_inventory() THEN RAISE EXCEPTION 'inventory admin access required'; END IF; IF jsonb_typeof(p_items)<>'array' OR jsonb_array_length(p_items)=0 THEN RAISE EXCEPTION 'at least one item is required'; END IF; INSERT INTO public.purchase_orders(requested_by,notes) VALUES(auth.uid(),coalesce(p_notes,'')) RETURNING id INTO v_id; FOR v_item IN SELECT * FROM jsonb_array_elements(p_items) LOOP IF nullif(v_item->>'bean_id','') IS NULL OR coalesce((v_item->>'quantity')::numeric,0)<=0 THEN RAISE EXCEPTION 'invalid purchase item'; END IF; INSERT INTO public.purchase_order_items(purchase_order_id,bean_id,quantity,unit_cost,source) VALUES(v_id,(v_item->>'bean_id')::uuid,(v_item->>'quantity')::numeric,coalesce((v_item->>'unit_cost')::numeric,0),coalesce(v_item->>'source','smart_reorder')); v_total:=v_total+((v_item->>'quantity')::numeric*coalesce((v_item->>'unit_cost')::numeric,0)); END LOOP; UPDATE public.purchase_orders SET total_estimated_cost=v_total,updated_at=now() WHERE id=v_id; RETURN v_id; END $$;
GRANT EXECUTE ON FUNCTION public.create_inventory_purchase_order(jsonb,text) TO authenticated;

CREATE OR REPLACE FUNCTION public.receive_inventory_purchase_order(p_order_id uuid, p_location_id uuid) RETURNS void LANGUAGE plpgsql SECURITY INVOKER SET search_path=public AS $$ DECLARE v_order public.purchase_orders; v_item record; v_inv public.bean_inventory; v_before numeric; v_after numeric; BEGIN IF NOT public.can_manage_inventory() THEN RAISE EXCEPTION 'inventory admin access required'; END IF; SELECT * INTO v_order FROM public.purchase_orders WHERE id=p_order_id FOR UPDATE; IF NOT FOUND THEN RAISE EXCEPTION 'purchase order not found'; END IF; IF v_order.status IN ('received','cancelled') THEN RAISE EXCEPTION 'purchase order cannot be received'; END IF; PERFORM 1 FROM public.inventory_locations WHERE id=p_location_id AND is_active=true; IF NOT FOUND THEN RAISE EXCEPTION 'inventory location not found'; END IF; FOR v_item IN SELECT * FROM public.purchase_order_items WHERE purchase_order_id=p_order_id LOOP INSERT INTO public.bean_inventory(bean_id,location_id,on_hand_qty,reserved_qty,incoming_qty) VALUES(v_item.bean_id,p_location_id,0,0,0) ON CONFLICT(bean_id,location_id) DO NOTHING; SELECT * INTO v_inv FROM public.bean_inventory WHERE bean_id=v_item.bean_id AND location_id=p_location_id FOR UPDATE; v_before:=v_inv.on_hand_qty; v_after:=v_before+v_item.quantity; UPDATE public.bean_inventory SET on_hand_qty=v_after,incoming_qty=GREATEST(0,incoming_qty-v_item.quantity),updated_at=now() WHERE id=v_inv.id; INSERT INTO public.inventory_transactions(bean_id,location_id,transaction_type,quantity,before_qty,after_qty,reference_type,reference_id,notes,created_by) VALUES(v_item.bean_id,p_location_id,'purchase_in',v_item.quantity,v_before,v_after,'purchase_order',p_order_id,'採購單入庫',auth.uid()); END LOOP; UPDATE public.purchase_orders SET status='received',updated_at=now() WHERE id=p_order_id; END $$;
GRANT EXECUTE ON FUNCTION public.receive_inventory_purchase_order(uuid,uuid) TO authenticated;
