import { useEffect, useMemo, useState } from 'react';
import { PackageSearch, RefreshCw } from 'lucide-react';
import { loadInventoryForecasts } from '../../services/inventoryService';
import { INVENTORY_STATUS } from '../../config/inventoryStatus';
import type { InventoryForecast, InventoryStatus } from '../../types/inventory';

const statuses: Array<InventoryStatus | 'all'> = ['all', 'critical', 'reorder', 'attention', 'normal'];
export default function AdminInventoryReorder() {
  const [rows, setRows] = useState<InventoryForecast[]>([]); const [filter, setFilter] = useState<InventoryStatus | 'all'>('all'); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const load = async () => { setLoading(true); setError(null); try { setRows(await loadInventoryForecasts()); } catch (e) { setError(e instanceof Error ? e.message : '庫存資料載入失敗'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const filtered = useMemo(() => rows.filter(r => filter === 'all' || r.status === filter), [rows, filter]);
  return <div className="space-y-6"><div className="flex items-center justify-between gap-3"><div><h1 className="text-2xl font-bold flex items-center gap-2"><PackageSearch className="text-[#C09A6A]" />智慧叫豆</h1><p className="text-sm text-gray-500 mt-1">依耗用、交期與安全庫存計算叫貨建議</p></div><button onClick={() => void load()} disabled={loading} className="px-4 py-2 rounded-xl border bg-white text-sm flex gap-2 items-center"><RefreshCw size={16} className={loading ? 'animate-spin' : ''} />重新整理</button></div>
  <div className="grid grid-cols-2 md:grid-cols-4 gap-3">{[['豆料品項', rows.length], ['建議叫貨', rows.filter(r => r.recommendedOrderQty > 0).length], ['急需叫貨', rows.filter(r => r.status === 'critical').length], ['資料更新', new Date().toLocaleTimeString('zh-TW')]].map(([label, value]) => <div key={String(label)} className="bg-white rounded-2xl p-4 border"><p className="text-xs text-gray-500">{label}</p><p className="text-xl font-bold mt-1">{value}</p></div>)}</div>
  <div className="flex gap-2 flex-wrap">{statuses.map(s => <button key={s} onClick={() => setFilter(s)} className={`px-3 py-2 rounded-xl border text-sm ${filter === s ? 'bg-[#C09A6A] text-white' : 'bg-white'}`}>{s === 'all' ? '全部' : INVENTORY_STATUS[s].label}</button>)}</div>{error && <div className="p-4 bg-red-50 text-red-700 rounded-xl">{error}</div>}
  <div className="bg-white border rounded-2xl overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead className="bg-gray-50"><tr>{['狀態','豆料 / SKU','供應商','現有 / 可用','近7天耗用','日均耗用','可用天數','建議叫貨','預計缺貨'].map(h => <th className="text-left px-4 py-3" key={h}>{h}</th>)}</tr></thead><tbody className="divide-y">{loading ? <tr><td colSpan={9} className="p-10 text-center">載入中...</td></tr> : filtered.length === 0 ? <tr><td colSpan={9} className="p-10 text-center text-gray-500">目前沒有資料</td></tr> : filtered.map(r => <tr key={r.beanId}><td className="px-4 py-4"><span className={`px-2 py-1 rounded-full text-xs ${INVENTORY_STATUS[r.status].className}`}>{INVENTORY_STATUS[r.status].label}</span></td><td className="px-4 py-4"><b>{r.name}</b><div className="text-xs text-gray-400">{r.sku}</div></td><td className="px-4 py-4">{r.supplierName || '未設定'}</td><td className="px-4 py-4">{r.onHandQty.toFixed(2)} / {r.availableQty.toFixed(2)} {r.unit}</td><td className="px-4 py-4">{r.usageLast7Days.toFixed(2)}</td><td className="px-4 py-4">{r.averageDailyUsage.toFixed(3)}</td><td className="px-4 py-4">{r.stockDays === null ? '—' : `${r.stockDays.toFixed(1)} 天`}</td><td className="px-4 py-4 font-semibold text-orange-700">{r.recommendedOrderQty ? `${r.recommendedOrderQty.toFixed(2)} ${r.unit}` : '—'}</td><td className="px-4 py-4">{r.predictedStockoutDate ? new Date(r.predictedStockoutDate).toLocaleDateString('zh-TW') : '—'}</td></tr>)}</tbody></table></div></div>;
}

