import { useEffect, useMemo, useState } from 'react';
import { PackageSearch, RefreshCw } from 'lucide-react';
import { createPurchaseOrderDraft, loadPurchaseOrderSummaries, loadInventoryLocations, receivePurchaseOrder, loadInventoryForecasts } from '../../services/inventoryService';
import type { PurchaseOrderSummary, InventoryLocationOption } from '../../services/inventoryService';
import { INVENTORY_STATUS } from '../../config/inventoryStatus';
import type { InventoryForecast, InventoryStatus } from '../../types/inventory';

const statuses: Array<InventoryStatus | 'all'> = ['all', 'critical', 'reorder', 'attention', 'normal'];
export default function AdminInventoryReorder() {
  const [rows, setRows] = useState<InventoryForecast[]>([]); const [creating, setCreating] = useState(false); const [purchaseOrders, setPurchaseOrders] = useState<PurchaseOrderSummary[]>([]); const [locations, setLocations] = useState<InventoryLocationOption[]>([]); const [locationId, setLocationId] = useState(''); const [receivingId, setReceivingId] = useState<string | null>(null); const [filter, setFilter] = useState<InventoryStatus | 'all'>('all'); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const load = async () => { setLoading(true); setError(null); try { const [forecast, orders, options] = await Promise.all([loadInventoryForecasts(), loadPurchaseOrderSummaries(), loadInventoryLocations()]); setRows(forecast); setPurchaseOrders(orders); setLocations(options); if (!locationId && options[0]) setLocationId(options[0].id); } catch (e) { setError(e instanceof Error ? e.message : '庫存資料載入失敗'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const receive = async (id: string) => { if (!locationId) return; setReceivingId(id); try { await receivePurchaseOrder(id, locationId); window.alert('入庫完成'); await load(); } catch (e) { window.alert(e instanceof Error ? e.message : '入庫失敗'); } finally { setReceivingId(null); } };
  const createDraft = async () => { const items = rows.filter(r => r.recommendedOrderQty > 0).map(r => ({ beanId: r.beanId, quantity: r.recommendedOrderQty, unitCost: 0 })); if (!items.length) return; setCreating(true); try { const id = await createPurchaseOrderDraft(items, '由智慧叫豆建立'); window.alert(`採購草稿已建立：${id}`); } catch (e) { window.alert(e instanceof Error ? e.message : '建立採購草稿失敗'); } finally { setCreating(false); } };
  const filtered = useMemo(() => rows.filter(r => filter === 'all' || r.status === filter), [rows, filter]);
  return <div className="space-y-6"><div className="flex items-center justify-between gap-3"><div><h1 className="text-2xl font-bold flex items-center gap-2"><PackageSearch className="text-[#C09A6A]" />智慧叫豆</h1><p className="text-sm text-gray-500 mt-1">依耗用、交期與安全庫存計算叫貨建議</p></div><button onClick={() => void load()} disabled={loading} className="px-4 py-2 rounded-xl border bg-white text-sm flex gap-2 items-center"><RefreshCw size={16} className={loading ? 'animate-spin' : ''} />重新整理</button><button onClick={() => void createDraft()} disabled={creating || !rows.some(r => r.recommendedOrderQty > 0)} className="px-4 py-2 rounded-xl bg-[#C09A6A] text-white text-sm disabled:opacity-50">{creating ? '建立中...' : '建立叫貨草稿'}</button></div>
  <div className="grid grid-cols-2 md:grid-cols-4 gap-3">{[['豆料品項', rows.length], ['建議叫貨', rows.filter(r => r.recommendedOrderQty > 0).length], ['急需叫貨', rows.filter(r => r.status === 'critical').length], ['資料更新', new Date().toLocaleTimeString('zh-TW')]].map(([label, value]) => <div key={String(label)} className="bg-white rounded-2xl p-4 border"><p className="text-xs text-gray-500">{label}</p><p className="text-xl font-bold mt-1">{value}</p></div>)}</div>
  <div className="flex gap-2 flex-wrap">{statuses.map(s => <button key={s} onClick={() => setFilter(s)} className={`px-3 py-2 rounded-xl border text-sm ${filter === s ? 'bg-[#C09A6A] text-white' : 'bg-white'}`}>{s === 'all' ? '全部' : INVENTORY_STATUS[s].label}</button>)}</div>{error && <div className="p-4 bg-red-50 text-red-700 rounded-xl">{error}</div>}
  <section className="bg-white border rounded-2xl p-4"><div className="flex flex-wrap items-center justify-between gap-3 mb-3"><h2 className="font-semibold">採購草稿與入庫</h2><select value={locationId} onChange={e => setLocationId(e.target.value)} className="rounded-lg border px-3 py-2 text-sm"><option value="">選擇入庫庫位</option>{locations.map(l => <option key={l.id} value={l.id}>{l.name}</option>)}</select></div>{purchaseOrders.length === 0 ? <p className="text-sm text-gray-500">尚無採購草稿</p> : <div className="space-y-2">{purchaseOrders.map(po => <div key={po.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-3 text-sm"><div><b>{po.orderNo}</b><span className="ml-3 text-gray-500">{po.itemCount} 項 · {new Date(po.createdAt).toLocaleDateString('zh-TW')}</span></div><div className="flex items-center gap-3"><span className="text-gray-600">{po.status}</span>{po.status !== 'received' && po.status !== 'cancelled' && <button onClick={() => void receive(po.id)} disabled={!locationId || receivingId === po.id} className="rounded-lg bg-emerald-600 px-3 py-1.5 text-white disabled:opacity-50">{receivingId === po.id ? '入庫中...' : '入庫'}</button>}</div></div>)}</div>}</section>
  <div className="bg-white border rounded-2xl overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead className="bg-gray-50"><tr>{['狀態','豆料 / SKU','供應商','現有 / 可用','近7天耗用','日均耗用','可用天數','建議叫貨','預計缺貨'].map(h => <th className="text-left px-4 py-3" key={h}>{h}</th>)}</tr></thead><tbody className="divide-y">{loading ? <tr><td colSpan={9} className="p-10 text-center">載入中...</td></tr> : filtered.length === 0 ? <tr><td colSpan={9} className="p-10 text-center text-gray-500">目前沒有資料</td></tr> : filtered.map(r => <tr key={r.beanId}><td className="px-4 py-4"><span className={`px-2 py-1 rounded-full text-xs ${INVENTORY_STATUS[r.status].className}`}>{INVENTORY_STATUS[r.status].label}</span></td><td className="px-4 py-4"><b>{r.name}</b><div className="text-xs text-gray-400">{r.sku}</div></td><td className="px-4 py-4">{r.supplierName || '未設定'}</td><td className="px-4 py-4">{r.onHandQty.toFixed(2)} / {r.availableQty.toFixed(2)} {r.unit}</td><td className="px-4 py-4">{r.usageLast7Days.toFixed(2)}</td><td className="px-4 py-4">{r.averageDailyUsage.toFixed(3)}</td><td className="px-4 py-4">{r.stockDays === null ? '—' : `${r.stockDays.toFixed(1)} 天`}</td><td className="px-4 py-4 font-semibold text-orange-700">{r.recommendedOrderQty ? `${r.recommendedOrderQty.toFixed(2)} ${r.unit}` : '—'}</td><td className="px-4 py-4">{r.predictedStockoutDate ? new Date(r.predictedStockoutDate).toLocaleDateString('zh-TW') : '—'}</td></tr>)}</tbody></table></div></div>;
}

